# Generated by Django 5.2.6 on 2025-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('sms', 'Sms'), ('email', 'Email')], default='email', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='ID из внешнего сервиса (SMS-провайдер, Telegram message_id и т.д.)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
