# Generated by Django 5.2.6 on 2025-09-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.AddField(
            model_name="notification",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[("telegram", "Telegram"), ("email", "Email")], default="email", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
